// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wndcgoaionugfqpvmede.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduZGNnb2Fpb251Z2ZxcHZtZWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzQyOTksImV4cCI6MjA2MzU1MDI5OX0.HE_kM_JpRPGjMx7t4RIMBbeNXp0lgiVrwhri9Dxk5Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);